# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


steps:
- task: DotNetCoreInstaller@0
  inputs:
     packageType: 'sdk'
     version: '17.2.32519.379'
- script: 'dotnet build ./ConsoleApp2.sln'
  displayName: 'Build Project'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
